# Generated by Django 3.2.6 on 2021-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=5)),
                ('source', models.CharField(max_length=50)),
                ('buy_price', models.DecimalField(decimal_places=6, max_digits=15)),
                ('sell_price', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
        ),
    ]
